package free.cobol2java.java;

/**
 * @author lidong@date 2024-08-22@version 1.0
 */
public enum RelationalOperator {
    GREATER, GREATER_OR_EQUAL,LESS, LESS_OR_EQUAL,EQUAL, NOT_EQUAL,MORETHANCHAR, LESSTHANCHAR, EQUALCHAR, NOTEQUALCHAR, MORETHANOREQUAL, LESSTHANOREQUAL
}
